name: Fork Setup Check

on:
  push:
    branches:
      - main
      - test-fork-workflow
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  fork_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup remote for upstream
        run: |
          git remote add upstream https://github.com/josefdc/pereiratechtalks.com || echo "Upstream already exists"

      - name: Verify fork is up to date
        run: |
          echo "Fetching upstream..."
          git fetch upstream
          echo "Checking for differences..."
          LOCAL=$(git rev-parse @)
          REMOTE=$(git rev-parse @{u})
          BASE=$(git merge-base @ @{u})
          if [ $LOCAL = $REMOTE ]; then
            echo "Fork is up to date with upstream."
          elif [ $LOCAL = $BASE ]; then
            echo "Fork is behind upstream. Consider syncing your fork."
          else
            echo "Fork has diverged from upstream. Consider rebasing or merging upstream."
          fi

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Provide feedback
        run: |
          echo "If your fork was behind or diverged from upstream, please sync it before making further contributions."
